# Generated by Django 5.2.11 on 2026-03-07 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='progresso',
            field=models.IntegerField(default=0, help_text='Progresso do projeto em porcentagem', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
